AWSTemplateFormatVersion: "2010-09-09"
Description: >
  AWS Lightsail container service for ARFID meal recommendation app.
  Deploys Flask web app + Celery worker containers.

Parameters:
  ServiceName:
    Type: String
    Description: Lightsail container service name (must be unique in region)
    Default: arfid-app

  Power:
    Type: String
    Default: micro
    AllowedValues: [nano, micro, small, medium, large, xlarge, 2xlarge]
    Description: >
      Lightsail power plan (CPU/RAM).
      nano = 0.25 vCPU, 512 MB ($7/mo)
      micro = 0.25 vCPU, 1 GB ($10/mo) - Recommended
      small = 0.5 vCPU, 2 GB ($40/mo)

  Scale:
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 20
    Description: Number of container replicas (horizontal scaling)

  Environment:
    Type: String
    Default: production
    AllowedValues: [production, staging, development]
    Description: Environment name for tagging

  HealthCheckPath:
    Type: String
    Default: /api/start
    Description: HTTP path used to determine container health

  ContainerPort:
    Type: Number
    Default: 8000
    Description: Port exposed by Flask application

  PublicDomainName:
    Type: String
    Default: ""
    Description: Optional custom domain name (e.g., arfid.yourdomain.com). Leave empty for default Lightsail domain.

Resources:
  # Main Lightsail Container Service
  ARFIDContainerService:
    Type: AWS::Lightsail::Container
    Properties:
      ServiceName: !Ref ServiceName
      Power: !Ref Power
      Scale: !Ref Scale
      IsDisabled: false
      Tags:
        - Key: Name
          Value: !Ref ServiceName
        - Key: Application
          Value: ARFID
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  ContainerServiceName:
    Description: Lightsail container service name
    Value: !Ref ARFIDContainerService
    Export:
      Name: !Sub "${AWS::StackName}-ServiceName"
  Url:
    Description: Public URL for the ARFID application
    Value: !GetAtt ARFIDContainerService.Url
    Export:
      Name: !Sub "${AWS::StackName}-ServiceUrl"
